version: '3.0'

services:
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=fv_user
      - RABBITMQ_DEFAULT_PASS=aVaras_08
